# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!

target 'iOS_Assignment' do 

    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Alamofire', '~> 5.0.0-beta.6'
end
